"""Ground-truth label registry for Phase 4.

Labels are the one thing ML cannot invent. This module reads them from exactly
one place: an operator-supplied file referenced by ``ML_LABEL_FILE``.

Why nothing else is acceptable
------------------------------
A label is a claim about what the traffic *actually was*. The capture itself
cannot prove that claim — that requires separate knowledge (a testbed record, a
labeled corpus manifest, a controlled experiment). So:

- Port numbers, filenames, directories, protocol names and traffic patterns are
  never label sources. Those are features at best; treating them as labels
  produces circular, meaningless accuracy.
- Synthetic captures generated by ``backend/tests/synthetic_pcap.py`` carry no
  ground truth, so they cannot be labeled here. They exercise the pipeline via
  the fixtures in the test suite, which inject labels explicitly and are scoped
  to tests.
- Phase 3 security findings are deterministic outputs, not labels.

If no label file is configured, the registry is empty and training reports
``INSUFFICIENT_LABELED_DATA``. That is the correct outcome, not a failure to
work around.

File format (YAML or JSON)
--------------------------
    label_source: user_provided
    feature_schema_version: "1.0"
    class_definition_version: "1.0"
    labels:
      - capture_id: CAP-000001        # human key from the captures table
        traffic_type: VOIP
      - capture_sha256: 3f9a...       # content hash; survives re-upload
        traffic_type: WEB
        note: "labelled from testbed run 2026-04-02"

``capture_id`` and ``capture_sha256`` are alternatives; a row may carry either
or both. Anything else fails validation rather than silently dropping the row.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from app.ml.schema import MLFeatureSchema, MLSchemaError


@dataclass(frozen=True)
class LabelRecord:
    traffic_type: str
    capture_key: str
    source: str
    note: str | None = None


@dataclass(frozen=True)
class LabelRegistry:
    source: str
    records: tuple[LabelRecord, ...]
    feature_schema_version: str | None
    class_definition_version: str | None
    rejected: tuple[dict[str, object], ...] = ()

    @property
    def is_empty(self) -> bool:
        return not self.records

    @property
    def by_capture_key(self) -> dict[str, LabelRecord]:
        return {record.capture_key: record for record in self.records}


def empty_registry() -> LabelRegistry:
    return LabelRegistry(
        source="none",
        records=(),
        feature_schema_version=None,
        class_definition_version=None,
    )


def load_label_registry(
    path: str | Path | None,
    schema: MLFeatureSchema,
) -> LabelRegistry:
    """Load the label file and validate every row against the schema classes.

    A malformed file raises. A single bad row is recorded in ``rejected`` so the
    caller can surface it, rather than being silently discarded.
    """
    if not path:
        return empty_registry()

    label_path = Path(path).expanduser()
    if not label_path.is_file():
        raise MLSchemaError(f"label file not found: {label_path}")

    text = label_path.read_text(encoding="utf-8")
    try:
        raw = json.loads(text) if label_path.suffix.lower() == ".json" else _load_yaml(text)
    except ValueError as exc:
        raise MLSchemaError(f"label file is not valid YAML/JSON: {label_path}") from exc

    if not isinstance(raw, dict):
        raise MLSchemaError("label file must contain a mapping at the top level")

    source = str(raw.get("label_source", "user_provided"))
    if source not in schema.label_sources:
        raise MLSchemaError(
            f"label_source {source!r} is not an accepted source {list(schema.label_sources)}"
        )

    schema_version = raw.get("feature_schema_version")
    if schema_version is not None and str(schema_version) != schema.feature_schema_version:
        raise MLSchemaError(
            "label file was built for feature_schema_version "
            f"{schema_version!r}, this pipeline uses {schema.feature_schema_version!r}"
        )

    class_version = raw.get("class_definition_version")
    if class_version is not None and str(class_version) != schema.class_definition_version:
        raise MLSchemaError(
            "label file was built for class_definition_version "
            f"{class_version!r}, this pipeline uses {schema.class_definition_version!r}"
        )

    entries = raw.get("labels", [])
    if not isinstance(entries, list):
        raise MLSchemaError("label file 'labels' must be a list")

    records: list[LabelRecord] = []
    rejected: list[dict[str, object]] = []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            rejected.append({"index": index, "reason": "row is not a mapping"})
            continue

        traffic_type = str(entry.get("traffic_type", "")).strip().upper()
        capture_id = entry.get("capture_id")
        capture_sha = entry.get("capture_sha256")

        if not traffic_type:
            rejected.append({"index": index, "reason": "missing traffic_type"})
            continue
        if schema.class_spec(traffic_type) is None:
            rejected.append(
                {
                    "index": index,
                    "reason": "unknown class for class_definition",
                    "traffic_type": traffic_type,
                }
            )
            continue
        if capture_id is None and capture_sha is None:
            rejected.append(
                {"index": index, "reason": "neither capture_id nor capture_sha256 provided"}
            )
            continue
        if capture_sha is not None and not _is_sha256(str(capture_sha)):
            rejected.append(
                {"index": index, "reason": "capture_sha256 is not a 64-char hex digest"}
            )
            continue

        for key in (capture_id, capture_sha):
            if key is None:
                continue
            records.append(
                LabelRecord(
                    traffic_type=traffic_type,
                    capture_key=str(key).strip(),
                    source=source,
                    note=entry.get("note"),
                )
            )

    return LabelRegistry(
        source=source,
        records=tuple(records),
        feature_schema_version=None if schema_version is None else str(schema_version),
        class_definition_version=None if class_version is None else str(class_version),
        rejected=tuple(rejected),
    )


def sha256_of_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _is_sha256(value: str) -> bool:
    if len(value) != 64:
        return False
    return all(char in "0123456789abcdefABCDEF" for char in value)


def _load_yaml(text: str) -> object:
    import yaml

    return yaml.safe_load(text)
