"""initial schema for captures, analysis_jobs, analyses, security_findings, reports

Revision ID: 921a9dd10bd6
Revises:
Create Date: 2026-09-23 10:43:45.672208
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "921a9dd10bd6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captures",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("capture_reference", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("capture_format", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            sa.Enum("UPLOADED", "ANALYZING", "ANALYZED", "FAILED", name="capture_status"),
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capture_reference"),
    )
    op.create_index(op.f("ix_captures_sha256"), "captures", ["sha256"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("capture_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PARTIAL", "FAILED", name="analysis_status"),
            nullable=False,
        ),
        sa.Column("protocol", sa.String(length=64), nullable=True),
        sa.Column("ike_version", sa.String(length=16), nullable=True),
        sa.Column("vpn_mode", sa.String(length=32), nullable=True),
        sa.Column("security_score", sa.Integer(), nullable=True),
        sa.Column("risk_level", sa.String(length=16), nullable=True),
        sa.Column("overall_confidence", sa.Float(), nullable=True),
        sa.Column("packet_count", sa.Integer(), nullable=True),
        sa.Column("flow_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summarization_json", sa.Text(), nullable=True),
        sa.Column("analyzer_version", sa.String(length=32), nullable=True),
        sa.Column("rule_version", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column("dataset_version", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyses_capture_id"), "analyses", ["capture_id"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("capture_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="job_status"),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column(
            "current_stage",
            sa.Enum(
                "INGESTION",
                "PROTOCOL_DETECTION",
                "FEATURE_EXTRACTION",
                "AI_ANALYSIS",
                "SECURITY_ASSESSMENT",
                "REPORT_GENERATION",
                "COMPLETED",
                name="job_stage",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_jobs_capture_id"), "analysis_jobs", ["capture_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum("EXECUTIVE", "TECHNICAL", "JSON", name="report_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "GENERATING", "READY", "FAILED", name="report_status"),
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_analysis_id"), "reports", ["analysis_id"], unique=False)
    op.create_table(
        "security_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "finding_type",
            sa.Enum(
                "VULNERABILITY_INDICATOR",
                "POLICY_DEVIATION",
                "CONFIGURATION_RISK",
                "INFORMATIONAL",
                "UNKNOWN",
                name="finding_type",
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence_json", sa.Text(), nullable=True),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_findings_analysis_id"), "security_findings", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_security_findings_category"), "security_findings", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_security_findings_rule_id"), "security_findings", ["rule_id"], unique=False
    )
    op.create_index(
        op.f("ix_security_findings_severity"), "security_findings", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_security_findings_status"), "security_findings", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_security_findings_status"), table_name="security_findings")
    op.drop_index(op.f("ix_security_findings_severity"), table_name="security_findings")
    op.drop_index(op.f("ix_security_findings_rule_id"), table_name="security_findings")
    op.drop_index(op.f("ix_security_findings_category"), table_name="security_findings")
    op.drop_index(op.f("ix_security_findings_analysis_id"), table_name="security_findings")
    op.drop_table("security_findings")
    op.drop_index(op.f("ix_reports_analysis_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_capture_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_analyses_capture_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_captures_sha256"), table_name="captures")
    op.drop_table("captures")

    # Drop the native PostgreSQL enum types created for the tables above.
    enum_names = [
        "capture_status",
        "analysis_status",
        "job_status",
        "job_stage",
        "report_type",
        "report_status",
        "severity",
        "finding_type",
    ]
    for enum_name in enum_names:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
